@development

### Registrar Usuario
POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "nombreUsuario": "elias_test9",
  "email": "elias@test9.com",
  "password": "123456"
}

### Generar Secreto 2FA
POST http://localhost:8080/api/auth/2fa-secret?username=elias_test9 HTTP/1.1
Content-Type: application/json

### Login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "nombreUsuario": "elias_test",
  "password": "123456"
}

### Login con 2FA (Obtener JWT y guardarlo)
POST http://localhost:8080/api/auth/login-2fa HTTP/1.1
Content-Type: application/json

{
  "nombreUsuario": "elias_test9",
  "token2FA": "122888"
}

#> {% 
#  const res = JSON.parse(responseBody);
#  client.global.set("jwt", res.token);
#%}

### Verificar 2FA
POST http://localhost:8080/api/auth/verify-2fa HTTP/1.1
Content-Type: application/json

{
  "nombreUsuario": "elias_test9",
  "token2FA": "072585"
}

### Test Update 2FA
POST http://localhost:8080/api/auth/test-update-2fa?nombreUsuario=elias_test HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Obtener Todos los Usuarios
GET http://localhost:8080/api/users HTTP/1.1
Authorization: Bearer {{jwt}}

### Obtener Usuario por ID
GET http://localhost:8080/api/users/2 HTTP/1.1
Authorization: Bearer {{jwt}}

### Actualizar Usuario (sin contraseña)
PUT http://localhost:8080/api/users/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "nombreUsuario": "elias duran",
  "email": "eliasefrain27@gmail.com"
}

### Actualizar Contraseña del Usuario
PUT http://localhost:8080/api/users/2/password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "currentPassword": "123456",
  "newPassword": "nuevaClave123"
}

### Eliminar Usuario por ID (borrado lógico)
DELETE http://localhost:8080/api/users/2 HTTP/1.1
Authorization: Bearer {{jwt}}

### ### Asignar variable global manualmente (Prueba)
### GET https://httpbin.org/anything HTTP/1.1
###
### > {% 
###   client.global.set("jwt", "valor_de_prueba");
### %}

### Probar variable jwt
GET https://httpbin.org/anything HTTP/1.1
Authorization: Bearer {{jwt}}