services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: ERP_Ventas
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrator
    depends_on:
      - db
    volumes:
      - ./db/sql:/flyway/sql
      - ./db/flyway.conf:/flyway/conf/flyway.conf
    command: migrate

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ERP_Ventas
      SPRING_DATASOURCE_USERNAME: erp_user
      SPRING_DATASOURCE_PASSWORD: erp_pass
    ports:
      - "8080:8080"
    depends_on:
      - db
      - flyway

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    ports:
      - "4200:4200"
      # - "4200:80"  # Producción con Nginx
    command: > # ⬅️ Solo se ejecuta en desarrollo
      ng serve
      --host 0.0.0.0
      --port 4200
      --disable-host-check

    # Uncomment the following lines for production with Nginx
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
    depends_on:
      - backend

volumes:
  postgres_data:
