services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_pass
      POSTGRES_DB: ERP_Ventas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migrator
    depends_on:
      - db
    command: migrate

  backend:
    image: erpventasacr.azurecr.io/erp-backend:latest
    container_name: spring_boot_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ERP_Ventas
      SPRING_DATASOURCE_USERNAME: erp_user
      SPRING_DATASOURCE_PASSWORD: erp_pass
    ports:
      - "8080:8080"
    depends_on:
      - db
      - flyway

  frontend:
    image: erpventasacr.azurecr.io/erp-frontend:latest
    container_name: angular_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: