name: CD - Despliegue a Azure VM

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.sha }}
      ACR: erpventasacr.azurecr.io

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Azure con Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Iniciar sesión en ACR
        run: |
          az acr login --name erpventasacr

      - name: Compilar imagen Backend
        run: |
          docker build -t $ACR/erp-backend:${TAG} ./backend
          docker tag $ACR/erp-backend:${TAG} $ACR/erp-backend:latest

      - name: Compilar imagen Frontend
        run: |
          docker build -t $ACR/erp-frontend:${TAG} ./frontend
          docker tag $ACR/erp-frontend:${TAG} $ACR/erp-frontend:latest

      - name: Subir imagen Backend a ACR
        run: |
          docker push $ACR/erp-backend:${TAG}
          docker push $ACR/erp-backend:latest

      - name: Subir imagen Frontend a ACR
        run: |
          docker push $ACR/erp-frontend:${TAG}
          docker push $ACR/erp-frontend:latest

      - name: Preparar docker-compose para producción
        run: cp docker-compose.prod.yml docker-compose.yml

      - name: Desplegar a la VM vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/azureuser/erp-ventas"

      - name: Ejecutar docker-compose pull + up vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/erp-ventas
            docker-compose pull
            docker-compose down --remove-orphans
            docker-compose up -d