name: CD - Despliegue a Azure VM

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Azure con Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Iniciar sesión en ACR
        run: |
          az acr login --name erpventasacr

      - name: Compilar imagen Backend
        run: |
          docker build -t erpventasacr.azurecr.io/erp-backend:latest ./backend

      - name: Compilar imagen Frontend
        run: |
          docker build -t erpventasacr.azurecr.io/erp-frontend:latest ./frontend

      - name: Subir imagen Backend a ACR
        run: |
          docker push erpventasacr.azurecr.io/erp-backend:latest

      - name: Subir imagen Frontend a ACR
        run: |
          docker push erpventasacr.azurecr.io/erp-frontend:latest

      - name: Desplegar a la VM vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/azureuser/erp-ventas"

      - name: Ejecutar docker-compose pull + up vía SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/erp-ventas
            docker compose pull
            docker compose down
            docker compose up -d