name: CI - ERP Ventas

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-backend:
    name: Validación del Backend
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache de dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Dar permisos de ejecución a mvnw
        working-directory: backend
        run: chmod +x mvnw

      - name: Instalar dependencias y compilar backend
        working-directory: backend
        run: ./mvnw clean install -DskipTests=false

      - name: Ejecutar pruebas del backend
        working-directory: backend
        run: ./mvnw test

  build-frontend:
    name: Validación del Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache de node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

        - name: Instalar dependencias frontend
          working-directory: frontend
          run: npm ci

        - name: Ejecutar pruebas del frontend
          working-directory: frontend
          run: npm test -- --watch=false --browsers=ChromeHeadless

        - name: Linter del código frontend
          working-directory: frontend
          run: npm run lint

      - name: Compilar frontend en modo producción
        working-directory: frontend
        run: npm run build -- --configuration production